---
- hosts: localhost
  become: yes
  vars:
    - user: 'andrc'
    - dotfiles_repo: 'git@github.com:andrecosta206/.dotfiles.git'
    - ssh_key: '.ssh/id_rsa'

  tasks:
    - name: "Install system packages"
      apt:
        name:
          - zsh
          - tmux
          - nvim
          - bat
          - exa
          - fzf
          - podman
          - git
        state: latest

    - name: "Install Python packages"
      pip:
        name:
          - poetry
        state: latest

    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ ansible_env.HOME }}/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        mode: "0600"

    - name: "Check out dotfiles from repository"
      git:
        repo: "{{ dotfiles_repo }}"
        dest: .dotfiles
        accept_hostkey: yes
        force: yes
        recursive: no
        key_file: "{{ ansible_env.HOME }}/{{ ssh_key }}"
      delegate_to: localhost
      become: no
      run_once: true
