- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include_tasks: tasks/ssh.yml,
      tasks/git-setup.yml,
      tasks/core-setup.yml,
      tasks/node-setup.yml,
      tasks/npm-packages.yml,
      tasks/zsh-setup.yml,
      tasks/nvim-setup.yml,
    # - include_task: tasks/zen.yml
    # - include_task: tasks/debugger.yml
      tasks/dotfiles.yml,
      tasks/productivity-tools.yml
    # - include_task: tasks/lsp.yml
