- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "andrcosta44@@gmail.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "andrcosta44"
  tags:
  - git-personal
- name: CTW
  git_config:
    name: user.email
    scope: global
    value: "TOBE_DEFINED"
  tags:
  - git-ctw
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "DONT_REMEMBER"
  tags:
  - git-ctw
