- name: Install pipx
  apt:
    name: pipx
  become: true
  tags:
    - install
    - python

- name: Ensure pipx binary path is added to shell
  shell: |
    pipx ensurepath
  args:
    executable: /bin/zsh
  tags:
    - install
    - python
